services:


  kafka:
    image: confluentinc/cp-server:7.0.1
    container_name: kafka-broker1
    restart: always
    ports:
      - "9092:9092"
      - "9094:9094"
    # volumes:
      # - ./kafka/data:/var/lib/kafka/data
      # - ./kafka/logs:/var/lib/kafka/logs
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:9092
    healthcheck:
      test: [ "CMD", "nc", "-z", "kafka", "9092" ]
      timeout: 45s
      interval: 10s
      retries: 10

  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    container_name: kafka-control-center
    hostname: control-center
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9021
    healthcheck:
      test: [ "CMD", "nc", "-z", "control-center", "9021" ]
      timeout: 45s
      interval: 10s
      retries: 10
