version: '3'
services:

  # HADOOP SERVICES
  namenode:
    extends:
      file: apache_hadoop_services.yml
      service: namenode

  datanode:
    extends:
      file: apache_hadoop_services.yml
      service: datanode
    depends_on:
      - namenode
      
  # HIVE SERVICES
  hive-metastore:
    extends:
      file: apache_hive_services.yml
      service: hive-metastore  
    depends_on:
      - namenode
      - datanode
      - postgres

  hive-server:
    extends:
      file: apache_hive_services.yml
      service: hive-server  
    depends_on:
      - hive-metastore


  hue:
    extends:
      file: apache_hadoop_services.yml
      service: hue  
    depends_on:
      - hive-server
      - postgres

  # SPARK SERVICES
  spark-master:
    extends:
      file: apache_spark_services.yml
      service: spark-master  

  spark-worker:
    extends:
      file: apache_spark_services.yml
      service: spark-worker
    depends_on:
      - spark-master


  nifi-node-01:
    extends:
      file: apache_nifi_services.yml
      service: nifi-node-01
    depends_on:
      - zookeeper

  # ######################################################
  # # AIRFLOW SERVICES

  postgres:
    extends:
      file: databases_services.yml
      service: postgres

  airflow:
    extends:
      file: apache_airflow_services.yml
      service: airflow

  # ######################################################
  # # KAFKA SERVICES

  zookeeper:
    extends:
      file: apache_zookeeper_services.yml
      service: zookeeper

  kafka:
    extends:
      file: apache_kafka_services.yml
      service: kafka
    depends_on:
      - zookeeper

  control-center:
    extends:
      file: apache_kafka_services.yml
      service: control-center
    depends_on:
      - kafka

######################################################
# NETWORK

networks:
  default:
    name: airflow-network
